/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfcheckout.gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.StyledDocument;
import selfcheckout.mysql.MySQLConn;

/**
 *
 * @author Gxara
 */
public class EmployeeDatabaseGUI extends javax.swing.JFrame
{
    StyledDocument doc;
    
    String product;
    
    //Connecting to the MySQL database
    MySQLConn connect = new MySQLConn();
    Connection conn = null;
    
    /**
     * Creates new form EmployeeDatabaseGUI
     */
    public EmployeeDatabaseGUI()
    {
        initComponents();
        
        AddToDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        idTextPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        firstnameTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        lastnameTextPane = new javax.swing.JTextPane();
        idLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idTextPane.setEditable(false);
        jScrollPane1.setViewportView(idTextPane);

        firstnameTextPane.setEditable(false);
        jScrollPane2.setViewportView(firstnameTextPane);

        lastnameTextPane.setEditable(false);
        jScrollPane3.setViewportView(lastnameTextPane);

        idLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        idLabel.setText("ID");

        firstnameLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        firstnameLabel.setText("FIRST NAME");

        lastnameLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lastnameLabel.setText("LAST NAME");

        backButton.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addGap(40, 40, 40)
                .addComponent(firstnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastnameLabel)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(firstnameLabel)
                    .addComponent(idLabel))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    
        EmployeeDatabaseGUI.this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

      //Will display all the employees in the Employee Database GUI
    private void AddToDB()
    {        
        try
        {
            //Number of rows for te ResultSet
            int rows = 0;
            //Connect and open the connection to the DB
            conn = connect.DBUtils();

            //Create the query and result set to get the results
            String query = "SELECT * FROM SelfCheckOut.Employees";
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            
            //Find the number of rows
            if(rs.last())
            {
                rows = rs.getRow();
                //Move the cursor to the beginning
                rs.beforeFirst();
            }
            
            for(int i = 0; i < rows; i++)
            {
                if(rs.next() != false)
                {
                    int id = rs.getInt("ID");
                    String firstname = rs.getString("First Name");
                    String lastname = rs.getString("Last Name");
                    
                    AddToEmployeeIds(id);
                    AddToEmployeeFirstNames(firstname);
                    AddToEmployeeLastNames(lastname);
                }    
            }    
        
        //Close the connections
        rs.close();
        conn.close();
        }
        
        catch (Exception ex)
        {
            Logger.getLogger(ProductDatabaseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    //Public method to add employee ids to the employee database
    public void AddToEmployeeIds(Integer id)
    {
        try
        {
            doc = this.idTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), id + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
     //Public method to add employee first names to the employee database
    public void AddToEmployeeFirstNames(String firstname)
    {
        try
        {
            doc = this.firstnameTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), firstname + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
     //Public method to add employee last names to the employee database
    public void AddToEmployeeLastNames(String lastname)
    {
        try
        {
            doc = this.lastnameTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), lastname + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDatabaseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextPane firstnameTextPane;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextPane idTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextPane lastnameTextPane;
    // End of variables declaration//GEN-END:variables
}
