/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfcheckout.gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.StyledDocument;
import selfcheckout.mysql.MySQLConn;

/**
 *
 * @author Gxara
 */
public class ProductDatabaseGUI extends javax.swing.JFrame
{
    StyledDocument doc;
    
    String product;
    
    //Connecting to the MySQL database
    MySQLConn connect = new MySQLConn();
    Connection conn = null;

    /**
     * Creates new form ProductDatabaseGUI
     */
    public ProductDatabaseGUI() {
        initComponents();
        
        AddToDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        nameTextPane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTextPane = new javax.swing.JTextPane();
        productPrice = new javax.swing.JScrollPane();
        priceTextPane = new javax.swing.JTextPane();
        nameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        idTextPane = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameTextPane.setEditable(false);
        nameTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(nameTextPane);

        categoryTextPane.setEditable(false);
        jScrollPane1.setViewportView(categoryTextPane);

        priceTextPane.setEditable(false);
        productPrice.setViewportView(priceTextPane);

        nameLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        nameLabel.setText("NAME");

        typeLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        typeLabel.setText("TYPE");

        priceLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        priceLabel.setText("PRICE");

        idTextPane.setEditable(false);
        jScrollPane2.setViewportView(idTextPane);

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setText("ID");

        backButton.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeLabel)
                        .addGap(130, 130, 130)
                        .addComponent(priceLabel)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(priceLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
         ProductDatabaseGUI.this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    //Will display all the items in the Product Database GUI
    private void AddToDB()
    {        
        try
        {
            //Number of rows for te ResultSet
            int rows = 0;
            //Connect and open the connection to the DB
            conn = connect.DBUtils();

            //Create the query and result set to get the results
            String query = "SELECT * FROM SelfCheckOut.Products";
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(query);
            rs.next();
            
            //Find the number of rows
            if(rs.last())
            {
                rows = rs.getRow();
                //Move the cursor to the beginning
                rs.beforeFirst();
            }
            
            for(int i = 0; i < rows; i++)
            {
                if(rs.next() != false)
                {
                    int id = rs.getInt("PID");
                    String name = rs.getString("Name");
                    String type = rs.getString("Type");
                    double price = rs.getDouble("Price");
                    
                    AddToProductIds(id);
                    AddToProductNames(name);
                    AddToProductTypes(type);
                    AddToProductPrices(price);
                }    
            }    
        
        //Close the connections
        rs.close();
        conn.close();
        }
        
        catch (Exception ex)
        {
            Logger.getLogger(ProductDatabaseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
     //Public method to add item ids to the product database
    public void AddToProductIds(Integer id)
    {
        try
        {
            doc = this.idTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), id + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
    //Public method to add item names to the product database
    public void AddToProductNames(String name)
    {
        try
        {
            doc = this.nameTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), name + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
     //Public method to add item types to the product database
    public void AddToProductTypes(String type)
    {
        try
        {
            doc = this.categoryTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), type + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    
        //Public method to add item types to the product database
    public void AddToProductPrices(Double price)
    {
        try
        {
            doc = this.priceTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), price + "\n", null);
        }
        catch(Exception ex)
        {
             System.out.println(ex); 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDatabaseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextPane categoryTextPane;
    private javax.swing.JTextPane idTextPane;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextPane nameTextPane;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextPane priceTextPane;
    private javax.swing.JScrollPane productPrice;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
